name: Test
on:
  push:
    branches:
      - main
      - v1*
      - v2*
  pull_request:
    branches:
      - main
      - v1*
      - v2*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check
      - run: pnpm run lint:all
      - run: pnpm run test:all
      - run: pnpm run test:e2e
      - run: pnpm run build:all
      - run: ./integration-tests.sh
